In [1]:
import numpy as np
import sympy as sp

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


# Onbayev Baurzhan (15 variant)

In [2]:
def f(x):
    return 2 * np.log(x + 5 ** (1 / 2)) * np.sinh(x)


a = 1
b = 3

x_1 = 1.24
x_2 = 1.97
x_3 = 2.54


# task 1

In [20]:
from functools import reduce
from typing import Callable, Iterable


class L_approx:
    def __init__(
        self,
        x_colleciton: Iterable[float],
        f: Callable,
    ) -> None:
        self.x_collection = x_colleciton
        self.y_collection = np.array([f(x) for x in x_colleciton])

    @staticmethod
    def w_prod(a, b):
        size_a, size_b = map(len, [a, b])
        c = np.zeros(size_a + size_b)
        for i in range(size_a):
            for j in range(size_b):
                c[i + j] += a[i] * b[j]

        return c

    @staticmethod
    def take_derivative(w):
        w_ = np.zeros_like(w)
        size = len(w)
        for i in range(1, size):
            w_[i] = w[i - 1] * (size - i)
        return w_

    @staticmethod
    def polynom(w, x):
        size = len(w)
        return sum([w[i] * x ** (size - i) for i in range(size)])

    # будет принимать строку - название метода построения
    # в классе будет словарь методов класса - разных методов построения полиномов
    def build_lagrange_polynom(
        self,
    ):
        self.w = reduce(
            lambda a, b: L_approx.w_prod(a, b), [[1, x] for x in self.x_collection]
        )
        print(self.w)
        self.w_d = L_approx.take_derivative(self.w)
        print(self.w_d)
        self.l_collection = [
            lambda x: L_approx.polynom(self.w, x)
            / (
                L_approx.polynom(self.w_d, x)
                * (x - self.x_collection[k] for k in range(len(self.x_collection)))
            )
        ]

    def approx(self, x):
        if hasattr(self, "l_collection"):
            return sum([f(x) for f in self.l_collection])


In [21]:
x_colleciton = np.array([a + k * (b - a) / 4 for k in range(0, 5)])
l_1_1 = L_approx(x_colleciton=x_colleciton, f=f)
l_1_1.x_collection, l_1_1.y_collection


(array([1. , 1.5, 2. , 2.5, 3. ]),
 array([ 2.76021621,  5.61292422, 10.4717287 , 18.81864376, 33.17060303]))

In [22]:
sa = L_approx.polynom(l_1_1.x_collection, 2)
L_approx.take_derivative(l_1_1.x_collection), sa


(array([0. , 4. , 4.5, 4. , 2.5]), 88.0)

In [23]:
l_1_1.build_lagrange_polynom()


[ 1.   10.   38.75 72.5  65.25 22.5   0.    0.    0.    0.  ]
[  0.     9.    80.   271.25 435.   326.25  90.     0.     0.     0.  ]


In [24]:
l_1_1.approx(1)


TypeError: unsupported operand type(s) for *: 'float' and 'generator'